# Examen de prácticas. Convocatoria Enero 2024

## Descomposición polar de una matriz

Como bien sabemos, todo número complejo $z$ se puede expresar en la forma $z = re^{j\theta}$, donde $r\geq 0$ y $e^{j\theta}$ es un punto del círculo unidad. De manera similar,  toma matriz cuadrada $A$ admite una factorización de la forma 
$$
A = Q S
$$
donde $Q$ es una matriz ortogonal (análogo al $e^{j\theta}$), y $S$ es una matriz simétrica y semidefinida positiva (análogo al $r$).

Esta factorización se llama **descomposición polar**. Se ultiliza frecuentemente en Mecánica de Sólidos, donde la matriz $A$ representa la deformación de un sólido, la cual se descompone en una rotación ($Q$) y unos estiramientos (o alargamientos) ($S$). También tiene aplicaciones en una parte de la Ciencia de Datos llamada Geometric Deep Learning. 


La factorización polar se pueda calcular muy fácilmente a partir de la factorización SVD. En efecto, se tiene:

$$
A = U\Sigma V^T = (UV^T)(V\Sigma V^T) = (Q)(S),
$$
es decir $Q = UV^T$ y $S = V\Sigma V^T$.

En este ejercicio calcularemos la factorización polar de una matriz dada usando estas ideas.

Introduce una matriz aleatoria de tamaño $3\times 3$ y llámala $A$. Imprime la matriz $A$ y el tipo de datos que contiene.

**Puntos = 1**



In [25]:
# Completar aquí

import numpy as np

A = np.random.randn(3, 3)
print(f"D = \n{A}")
print(f"Tipo de datos en A = {A.dtype}")

# Fin Completar aquí ------------------------------------


D = 
[[-6.43715406e-01  1.05207692e+00  1.55320952e+00]
 [ 4.55200934e-01  4.94946473e-01  1.90047335e-04]
 [-2.04271403e+00 -1.37231416e+00  1.07054948e+00]]
Tipo de datos en A = float64


Calcula la factorización SVD de $A$. Imprime las matrices $U$, $\Sigma$ y $V^T$.

**Puntos = 2**



In [1]:
# Completar aquí

from scipy.linalg import svd

U, s, V_T = svd(A)

Sigma = np.zeros((A.shape[0], A.shape[1]))

# rellenamos Sigma con las valores singulares
Sigma[:A.shape[0], :A.shape[0]] = np.diag(s)

print(f"U = \n {U}")
print(f"S = \n {Sigma}")
print(f"V^T = \n {V_T}")

# Fin Completar aquí ------------------------------------

NameError: name 'A' is not defined

Calcula la descomposición polar de $A$ según se ha explicado anteriormente. Has de imprimir las matrices $Q$ y $S$ y comprobar que, salvo errores de redondeo/representación, se cumple que $A = Q S$

**Puntos = 2**

In [27]:
# Completar aquí

Q = U @ V_T
S = V_T.T @ Sigma @ V_T
print(f"Q = \n {Q}")
print(f"S = \n {S}")

np.allclose(A, Q @ S)


# Fin Completar aquí ------------------------------------

Q = 
 [[-0.30540673  0.69550008  0.6503894 ]
 [ 0.76296705 -0.2299405   0.60415946]
 [-0.56974381 -0.68074004  0.46041827]]
S = 
 [[ 1.70772201  0.83818398 -1.08415458]
 [ 0.83818398  1.55210054  0.35144775]
 [-1.08415458  0.35144775  1.50320636]]


True

Se puede demostrar que la matriz $Q$ de la descomposición polar es la matriz ortogonal más próxima a $A$ para la norma de Frobenius, es decir, dada $A$ la solución del problema
$$
\text{Minimizar } \Vert A- Z\Vert
$$
entre todas las matrices ortogonales $Z$, tiene como solución $Z=Q$.

A continuación haremos una pequeña comprobación de este hecho. Se pide:

1) **(puntos = 2)** Introduce **en formato sparse** la siguiente matriz
$$
Z = \left[
    \begin{array}{ccc}
    0.8 & 0.6 & 0 \\ 
    -0.6 & 0.8 & 0 \\
    0    & 0   & 1
    \end{array}
    \right]
$$
e imprímela tanto en formato sparse como dense.

2) **(puntos = 2)** Comprueba que $Z$ es ortogonal. Justifica la respuesta haciendo uso de la inversa de $Z$.

3) **(puntos = 1)** Comprueba que, para la norma de Frobenius, se cumple que

$$
\Vert A - Q\Vert < \Vert A - Z\Vert 
$$


In [28]:
# Completar aquí
from scipy.sparse import csr_matrix
row = np.array([0, 0, 1, 1, 2])
col = np.array([0, 1, 0, 1, 2])
data = np.array([0.8, 0.6, -0.6, 0.8, 1])

Z_sparse = csr_matrix((data, (row, col)), shape=(3, 3))
Z_dense = Z_sparse.todense()

print(f"Matriz Z en formato sparse = \n {Z_sparse}") 
print(f"Matriz Z en formato dense = \n {Z_dense}")

# Para ver que Z es ortogonal hemos de comprobar que su inversa coincide
# con su traspuesta
inversa_Z = np.linalg.inv(Z_dense)
np.allclose(inversa_Z, Z_dense.T)

norma_AQ = np.linalg.norm(A - Q, "fro")
print(f"norma de Frobenius de A - Q = {norma_AQ}")

norma_AZ = np.linalg.norm(A - Z_dense, "fro")
print(f"norma de Frobenius de A - Z = {norma_AZ}")


# Fin Completar aquí ------------------------------------

Matriz Z en formato sparse = 
   (0, 0)	0.8
  (0, 1)	0.6
  (1, 0)	-0.6
  (1, 1)	0.8
  (2, 2)	1.0
Matriz Z en formato dense = 
 [[ 0.8  0.6  0. ]
 [-0.6  0.8  0. ]
 [ 0.   0.   1. ]]
norma de Frobenius de A - Q = 2.24984893834289
norma de Frobenius de A - Z = 3.459560408291547
