In [1]:
# Completar aquí
import numpy as np

A = np.array([
    [3., -4.], 
    [7., -6.]
])
print(f"A = \n {A}")
print(f"tipo de datos en A = {A.dtype}")

B = np.array([
    [7., 1.], 
    [0., -7.]
])
print(f"B = \n {B}")
print(f"tipo de datos en B = {B.dtype}")
# Fin Completar aquí ------------------------------------

A = 
 [[ 3. -4.]
 [ 7. -6.]]
tipo de datos en A = float64
B = 
 [[ 7.  1.]
 [ 0. -7.]]
tipo de datos en B = float64


In [2]:
# Completar aquí
C = np.vstack((A, B))
print(f"C = \n {C}")
# Fin Completar aquí ------------------------------------

C = 
 [[ 3. -4.]
 [ 7. -6.]
 [ 7.  1.]
 [ 0. -7.]]


In [3]:
# Completar aquí
from numpy.linalg import qr

Q, R = qr(C)

print(f"Q = \n {Q}")
print(f"R = \n {R}")
# Fin Completar aquí ------------------------------------

Q = 
 [[-0.29002095 -0.2973758 ]
 [-0.67671554 -0.32431577]
 [-0.67671554  0.45176254]
 [-0.         -0.7760783 ]]
R = 
 [[-10.34408043   4.5436615 ]
 [  0.           9.01970843]]


In [4]:
# Completar aquí
Q_1 = Q[:2, :]
print(f"Q_1 = \n {Q_1}")

Q_2 = Q[2:, :]
print(f"Q_2 = \n {Q_2}")
# Fin Completar aquí ------------------------------------

Q_1 = 
 [[-0.29002095 -0.2973758 ]
 [-0.67671554 -0.32431577]]
Q_2 = 
 [[-0.67671554  0.45176254]
 [-0.         -0.7760783 ]]


In [6]:
from scipy.linalg import svd

U_1, s_1, V_1_T = svd(Q_1)

# creamos una matriz de zeros de tamaño m x n 
Sigma_1 = np.zeros((Q_1.shape[0], Q_1.shape[0]))

# rellenamos S con los valores singulares
Sigma_1[:Q_1.shape[0], :Q_1.shape[0]] = np.diag(s_1)

print(f"tamaño de U_1 = {U_1.shape}")
print(f"tamaño de  Sigma_1 = {Sigma_1.shape}")
print(f"tamaño V_1^T = {V_1_T.shape}")
print(f"valores singulares de Q_1 = {s_1}")
print(f"U_1 = \n {U_1}")
print(f"V_1^T = \n {V_1_T}")
print(f"U_1 S_1 V_1^T = \n {U_1.dot(Sigma_1.dot(V_1_T))}")
# Fin Completar aquí ------------------------------------

tamaño de U_1 = (2, 2)
tamaño de  Sigma_1 = (2, 2)
tamaño V_1^T = (2, 2)
valores singulares de Q_1 = [0.84835582 0.12633904]
U_1 = 
 [[-0.47169825 -0.88176003]
 [-0.88176003  0.47169825]]
V_1^T = 
 [[ 0.86461727  0.50243107]
 [-0.50243107  0.86461727]]
U_1 S_1 V_1^T = 
 [[-0.29002095 -0.2973758 ]
 [-0.67671554 -0.32431577]]


In [1]:
import numpy as np
