# Práctica 8: Ejercicio para entregar. 
## Factorizaciones LU y Choleski. Aplicación a la resolución de sistemas lineales.



Una clase importante de matrices que aparecen muy frecuentemente en varios campos de la Ingeniería son las llamadas **matrices de Toeplitz**. En dimensión $5$, esta matriz es:
$$
T_5 = \left[\begin{array}{ccccc}
2 & -1 & 0 & 0 & 0\\
-1 & 2 & -1 & 0 & 0\\
0 & -1 & 2 & -1 & 0\\
0 & 0 & -1 & 2 & -1\\
0 & 0 & 0 & -1 & 2
\end{array}
\right]
$$


1) Introduce esta matriz en formato sparse y utilizando el método csr_matrix

2) Tranforma la matriz a formato dense y denota a la matriz resultante con la letra $T$



In [2]:
# Completar aquí
from scipy.sparse import csr_matrix
import numpy as np


M = np.array([
    [2, -1, 0, 0, 0],
    [-1, 2, -1, 0, 0],
    [0, -1, 2, -1, 0],
    [0, 0, -1, 2, -1],
    [0, 0, 0, -1, 2]
    ])

T5 = csr_matrix(M)
print(f"La matriz sparse en formato csr = \n {T5}")

T = T5.todense()
print(f"T = \n {T}")
# --------------------


La matriz sparse en formato csr = 
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13 stored elements and shape (5, 5)>
  Coords	Values
  (0, 0)	2
  (0, 1)	-1
  (1, 0)	-1
  (1, 1)	2
  (1, 2)	-1
  (2, 1)	-1
  (2, 2)	2
  (2, 3)	-1
  (3, 2)	-1
  (3, 3)	2
  (3, 4)	-1
  (4, 3)	-1
  (4, 4)	2
T = 
 [[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]


1) Comprueba, usando un operador booleano, que $T$ es simétrica

2) Comprueba que $T$ es no singular

3) Calcula el número de condicionamiento de $T$


In [28]:
# Completar aquí
print("¿Es la matriz T simétrica?")
print(T == T.T)


det_T = np.linalg.det(T)
print(f"El determinante de T = {det_T}")
print("Al ser diferente de 0 no es singular")


cond_T = np.linalg.cond(T)
print(f"El condicionamiento de T es = {cond_T}")



# --------------------


¿Es la matriz T simétrica?
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
El determinante de T = 6.0
Al ser diferente de 0 no es singular
El condicionamiento de T es = 13.92820323027552


Calcula la descomposición $PLU$ de $T$ y comprueba que $T = PLU$ 
haciendo uso de un operador booleano. 



In [31]:
# Completar aquí
from scipy.linalg import lu
P, L, U = lu(T)

print(f"P = \n {P}")
print(f"L = \n {L}")
print(f"U = \n {U}")

LU = np.dot(L, U)
PLU = np.dot(P, LU)
print(f"La matriz PLU = \n {PLU}")

print(PLU == T)
# --------------------


P = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
L = 
 [[ 1.          0.          0.          0.          0.        ]
 [-0.5         1.          0.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.          0.        ]
 [ 0.          0.         -0.75        1.          0.        ]
 [ 0.          0.          0.         -0.8         1.        ]]
U = 
 [[ 2.         -1.          0.          0.          0.        ]
 [ 0.          1.5        -1.          0.          0.        ]
 [ 0.          0.          1.33333333 -1.          0.        ]
 [ 0.          0.          0.          1.25       -1.        ]
 [ 0.          0.          0.          0.          1.2       ]]
La matriz PLU = 
 [[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True 

Calcula la factorización de Choleski de $T$

In [ ]:
# Completar aquí
from scipy.linalg import ldl

L, D, P = ldl(T) #P es una matriz de permutación
print(f"L = \n {L}")
print(f"D = \n {D}")
print(f"P = \n {P}")

LD = np.dot(L, D)
print(f"LD = \n {LD}")

LDL_T = np.dot(LD, L.T)
print(f"LDL^T = \n {LDL_T}")
# --------------------


L = 
  [[ 1.          0.          0.          0.          0.        ]
 [-0.5         1.          0.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.          0.        ]
 [ 0.          0.         -0.75        1.          0.        ]
 [ 0.          0.          0.         -0.8         1.        ]]
D = 
 [[2.         0.         0.         0.         0.        ]
 [0.         1.5        0.         0.         0.        ]
 [0.         0.         1.33333333 0.         0.        ]
 [0.         0.         0.         1.25       0.        ]
 [0.         0.         0.         0.         1.2       ]]
P = 
  [0 1 2 3 4]
LD = 
 [[ 2.          0.          0.          0.          0.        ]
 [-1.          1.5         0.          0.          0.        ]
 [ 0.         -1.          1.33333333  0.          0.        ]
 [ 0.          0.         -1.          1.25        0.        ]
 [ 0.          0.          0.         -1.          1.2       ]]
LDL^T = 
 [[ 2. -1.  0.  0.  0.]
 [-1.

1) Resuelve el sistema $T^2x = b$, donde $b = \left[ 0, 0, -1, 0, 0\right]^T$

2) Comprueba mediante un operador booleano si $T^2x = b$. Explica a qué se debe el resultado que has obtenido y averigua la forma de resolverlo. Puede resultar útil usar el método np.round()

In [34]:
# Completar aquí
from scipy.linalg import solve


TxT = np.dot(T, T)
print(f"T^2 = \n {TxT}")
b_notrasp = np.array([0, 0, -1, 0, 0])
b = b_notrasp.reshape((5, 1))

x = solve(TxT, b)
print(f"x = \n {x}")

T2x = np.dot(TxT, x)

print(f"Ax = b = \n {T2x == b}")
"""EL primer resultado se debe a un error de la máquina, ya que esta es límitada, 
y al hacer los cálculos se va dejando decimales que hace que las matrices no sean 
iguales. Como el error es tan pequeño, podemos hacer un np.round para redondear 
las cifras y que al igualar ambos vectores hacer que se cumpla la igualdad. """

print(f"Redondeadas = \n {np.round(T2x) == np.round(b)}")






# --------------------


T^2 = 
 [[ 5 -4  1  0  0]
 [-4  6 -4  1  0]
 [ 1 -4  6 -4  1]
 [ 0  1 -4  6 -4]
 [ 0  0  1 -4  5]]
x = 
 [[-2.25]
 [-4.  ]
 [-4.75]
 [-4.  ]
 [-2.25]]
Ax = b = 
 [[ True]
 [False]
 [False]
 [False]
 [False]]
Redondeadas = 
 [[ True]
 [ True]
 [ True]
 [ True]
 [ True]]
