# Práctica 7: Ejercicio para entregar. 
## Tensores en Ciencia de Datos.



El fichero la_manga.jpg contiene dos fotos de La Manga del Mar Menor, una de los años 60 y otra actual. 

![imagen de La Manga del Mar Menor en los años 60 y en la actualidad](../data/la_manga.jpg)

Carga dicho fichero y convierte la imagen en un tensor. A continuación, imprime por pantalla el tensor asociado a la imagen y guárdalo en la carpeta data con el nombre **tensor_la_manga.npy**



In [1]:
# Completar aquí
from PIL import Image
import numpy as np

img = Image.open("../data/la_manga.jpg")
imgArray = np.array(img)
# --------------------


In [4]:
print(f"El tensor es = \n {imgArray}")

El tensor es = 
 [[[192 192 192]
  [190 190 190]
  [189 189 189]
  ...
  [149 176 195]
  [149 176 195]
  [149 176 195]]

 [[193 193 193]
  [191 191 191]
  [189 189 189]
  ...
  [148 175 194]
  [148 175 194]
  [148 175 194]]

 [[194 194 194]
  [192 192 192]
  [190 190 190]
  ...
  [146 173 192]
  [146 173 192]
  [146 173 192]]

 ...

 [[184 184 184]
  [143 143 143]
  [121 121 121]
  ...
  [ 59  89  81]
  [ 63  90  83]
  [ 61  91  83]]

 [[174 174 174]
  [133 133 133]
  [119 119 119]
  ...
  [ 63  94  86]
  [ 66  96  88]
  [ 66  97  89]]

 [[160 160 160]
  [123 123 123]
  [117 117 117]
  ...
  [ 67  98  90]
  [ 70 101  93]
  [ 70 101  93]]]


In [5]:
np.save("../data/tensor_la_manga.npy", imgArray)

Calcula la forma y dimensión del tensor generado. 

In [6]:
# Completar aquí
print(f"La forma del tensor es = {imgArray.shape}")
print(f"La dimensión del vector = {imgArray.ndim}")
# --------------------

La forma del tensor es = (720, 960, 3)
La dimensión del vector = 3


Utiliza la técnica de **slicing** que vimos en la práctica 3 para generar dos vectores. Uno de ellos, denotado **v1** se ha de corresponder con la primera fila del tensor que ves por pantalla; el segundo vector, **v2**, está formado por la segunda fila que ves por pantalla.  

In [8]:
# Completar aquí
v1 = imgArray[0, 0, :]
v2 = imgArray[0, 1, :]
print(f"v1 = {v1}")
print(f"v2 = {v2}")
# --------------------


v1 = [192 192 192]
v2 = [190 190 190]


Calcula:

1) el producto tensorial de **v1** y **v2**

2) el producto de Hadamard de **v1** y **v2**

3) el producto escalar de **v1** y **v2**

In [16]:
# Completar aquí
C = np.tensordot(v1, v2, axes=0)
print(f"Producto tensorial de v1 y v2 = \n {C}")

print(f"v1 * v2 = \n {v1 * v2}")

print(f"El producto escalat de v1 y v2 = {v1.dot(v2)}")

# --------------------


Producto tensorial de v1 y v2 = 
 [[128 128 128]
 [128 128 128]
 [128 128 128]]
v1 * v2 = 
 [128 128 128]
El producto escalat de v1 y v2 = 128


Introduce manualmente, usando **np.array()**, los vectores **v1** y **v2** anteriores y denótaos por **z1** y **z2**, respectivamente.

A contrinuación realiza los mismos cálculos (producto tensorial, producto de Hadamard y producto escalar) con los vectores **z1** y **z2**.

In [11]:
# Completar aquí
z1 = np.array([192, 192, 192])
z2 = np.array([190, 190, 190])
print(f"z1 = {z1}")
print(f"z2 = {z2}")

C = np.tensordot(z1, z2, axes=0)
print(f"Producto tensorial de z1 y z2 = \n {C}")

print(f"z1 * z2 = \n {z1 * z2}")

print(f"El producto escalat de z1 y z2 = {z1.dot(z2)}")
# --------------------


z1 = [192 192 192]
z2 = [190 190 190]
Producto tensorial de z1 y z2 = 
 [[36480 36480 36480]
 [36480 36480 36480]
 [36480 36480 36480]]
z1 * z2 = 
 [36480 36480 36480]
El producto escalat de z1 y z2 = 109440


Como puedes ver, obtienes resultados distintos. 

Busca una explicación convincente para esta discrepancia de resultados.
Te puede resultar útil estudiar los atributos **shape**, **type** y **dtype** de los vectores **v1**, **v2**, **z1** y **z2**.

Investiga y dí todo lo que sepas sobre este asunto.

In [17]:
# Completar aquí
print(v1.shape)
print(z1.shape)
print(v2.shape)
print(z2.shape)
print(v1.dtype)
print(z1.dtype)
print(v2.dtype)
print(z2.dtype)
print(type(v1))
print(type(z1))
print(type(v2))
print(type(z2))

"""La diferencia se encuentra en el tipo de dato, en el caso de v1 y v2 es uint8, 
el cual solo representa los números desde el 0 hasta el 255 ya que es un tensor 
de una imagen RGB, este esta en base 256 por lo que todos los números toman valores hasta 255.
 Sin embargo, el z1 y z2 es int 64 y puede representar números más grandes"""
# --------------------


(3,)
(3,)
(3,)
(3,)
uint8
int64
uint8
int64
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


'La diferencia se encuentra en el tipo de dato, en el caso de v1 y v2 es uint8, \nel cual solo representa los números desde el 0 hasta el 255 ya que es un tensor \nde una imagen RGB, este esta en base 256 por lo que todos los números toman valores hasta 255.\n Sin embargo, el z1 y z2 es int 64 y puede representar números más grandes'