# Práctica 9: Ejercicio para entregar. 
## Métodos iterativos para la resolución de sistemas lineales


Consideremos la matriz de Toeplitz en dimensión $n$:
$$
K_n = \left[
    \begin{array}{ccccccc}
    2 & -1 & 0 & 0 & 0 & \cdots & 0 \\ 
    -1 & 2 & -1 & 0 & 0 &\cdots & 0 \\
    0 & -1 & 2 & -1 & 0 &\cdots & 0 \\
    \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
    0 & 0 & 0 & \cdots & -1 & 2 & -1\\
    0 & 0 & 0 & \cdots & 0 & -1 & 2\\
    \end{array}
    \right]
$$

Define una función cuya entrada sea $n$, y cuya salida sea la matriz de Toeplitz en dimensión $n$. Has de usar los métodos de Python sobre matrices **sparse**, en concreto **csr_matrix**.

Ejecuta dicha función para el caso $n=6$ e imprime el resultado en pantalla y en forma matriz densa, para asegurarte que está bien implmentada.

In [3]:
import numpy as np
from scipy.sparse import csr_matrix

In [4]:
# Completar aquí
def MyToeplitzSparse(n):
    filaindex = np.zeros([4 + (n - 2) * 3])
    columnindex = np.zeros([4 + (n - 2) * 3])
    data = np.zeros([4 + (n - 2) * 3])
    
    filaindex[0] = 0
    columnindex[0] = 0
    data[0] = 2

    filaindex[1] = 0
    columnindex[1] = 1
    data[1] = -1

    filaindex[2 + 3*(n - 2)] = n - 1
    columnindex[2 + 3*(n - 2)] = n - 2
    data[2 + 3*(n - 2)] = -1

    filaindex[2 + 3*(n - 2) + 1] = n - 1
    columnindex[2 + 3*(n - 2) + 1] = n - 1
    data[2 + 3*(n - 2) + 1] =  2

    for i in range(2, n):
        filaindex[2 + (i - 2) * 3 + 0] = i - 1
        filaindex[2 + (i - 2) * 3 + 1] = i - 1
        filaindex[2 + (i - 2) * 3 + 2] = i - 1  

        columnindex[2 + 3*(i - 2) + 0] = i - 2
        columnindex[2 + 3*(i - 2) + 1] = i - 1
        columnindex[2 + 3*(i - 2) + 2] = i

        data[2 + 3*(i - 2) + 0] = -1
        data[2 + 3*(i - 2) + 1] = 2
        data[2 + 3*(i - 2) + 2] = - 1
    
    k = csr_matrix((data, (filaindex, columnindex)), shape=(n, n))
    return k
k = MyToeplitzSparse(6)
S = k.todense()
print(f"Formato Sparse = \n {k}")
print(f"Formato Dense \n {S}")

Formato Sparse = 
   (np.int32(0), np.int32(0))	2.0
  (np.int32(0), np.int32(1))	-1.0
  (np.int32(1), np.int32(0))	-1.0
  (np.int32(1), np.int32(1))	2.0
  (np.int32(1), np.int32(2))	-1.0
  (np.int32(2), np.int32(1))	-1.0
  (np.int32(2), np.int32(2))	2.0
  (np.int32(2), np.int32(3))	-1.0
  (np.int32(3), np.int32(2))	-1.0
  (np.int32(3), np.int32(3))	2.0
  (np.int32(3), np.int32(4))	-1.0
  (np.int32(4), np.int32(3))	-1.0
  (np.int32(4), np.int32(4))	2.0
  (np.int32(4), np.int32(5))	-1.0
  (np.int32(5), np.int32(4))	-1.0
  (np.int32(5), np.int32(5))	2.0
Formato Dense 
 [[ 2. -1.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0. -1.  2.]]


Genera dos ficheros con extensión .py

El primero de ellos se ha de llamar jacobi.py y ha de contener la función jacobi que está en la práctica 9. El segundo se ha de llamar gauss_seidel.py y ha de contener la función gauss_seidel de la misma práctica.

Importa ambas funciones a este fichero. Por ejemplo, para jacobi.py, esto se hace así: **from jacobi import jacobi**. Lo mismo para gauss-seidel.

Toma $n$ igual a las dos últimas cifras de tu DNI y genera un 1d-array (vector) de dimensión $n$ con todas sus componentes igual a 1. Denótalo $b$.

Se muestran a continuación los resultados para $n=66$.

In [5]:
# Completar aquí
from jacobi import jacobi
from gauss_seidel import gauss_seidel

n = 66
b = np.ones([n])
# --------)------------


Para el valor de $n$ que has tomado anteriormente, resuelve el sistema $K_n x = b$ mediante ambos, los métodos de Jacobi y Gauss-Seidel, y haciendo uso de las funciones que acabas de importar.



In [7]:
# Completar aquí
m = MyToeplitzSparse(n)
K = m.todense()

x_jacobi = jacobi(K, b)
x_gauss_seidel = gauss_seidel(K, b)
# --------------------


In [8]:
print(f"X en Jacobi{x_jacobi}")
print(f"X en Gauss-Seidel{x_gauss_seidel}")

X en Jacobi[ 32.99954534  64.99909169  95.99864003 125.99819136 154.99774666
 182.99730692 209.9968731  235.99644615 260.99602702 284.99561661
 307.99521585 329.9948256  350.99444672 370.99408005 389.9937264
 407.99338653 424.99306121 440.99275113 455.99245699 469.99217944
 482.99191907 494.99167647 505.99145216 515.99124665 524.99106037
 532.99089375 539.99074714 545.99062088 550.99051523 554.99043043
 557.99036667 559.99032408 560.99030277 560.99030277 559.99032408
 557.99036667 554.99043043 550.99051523 545.99062088 539.99074714
 532.99089375 524.99106037 515.99124665 505.99145216 494.99167647
 482.99191907 469.99217944 455.99245699 440.99275113 424.99306121
 407.99338653 389.9937264  370.99408005 350.99444672 329.9948256
 307.99521585 284.99561661 260.99602702 235.99644615 209.9968731
 182.99730692 154.99774666 125.99819136  95.99864003  64.99909169
  32.99954534]
X en Gauss-Seidel[ 32.99999877  64.99999754  95.99999631 125.9999951  154.99999391
 182.99999273 209.99999156 235.99999

In [9]:
# Completar aquí
diferencia = (x_jacobi - x_gauss_seidel)
norm2 = np.linalg.norm(diferencia, 2)
norminf = np.linalg.norm(diferencia, +(np.inf))
print(f"La norma euclidea = {norm2}")
print(f"La norma infinita = {norminf}")


# --------------------


La norma euclidea = 0.055995085403849204
La norma infinita = 0.009671834780192512
