# Práctica 2: Ejercicio para entregar 

## Introducción a N-dimensional arrays en Python


Partimos de tu número de DNI, que debe contener 9 dígitos.
DNI = abcdefgh  . Por ejemplo, DNI = 23982606

Introduce tu DNI en forma de 1d-array e imprimelo junto con sus atributos forma, tamaño y tipo

In [2]:
import numpy as np

In [9]:
# Completar aquí
dni = np.array([2, 9, 5, 2, 9, 0, 7, 9])
print(f"dni = {dni}")
print(type(dni))
print(dni.shape)
print(dni.size)
print(dni.dtype)

# --------------------


dni = [2 9 5 2 9 0 7 9]
<class 'numpy.ndarray'>
(8,)
8
int64


Define e imprimer los siguientes ndarrays:

1) Una matriz cuadrada de unos y de tamaño el dígito más grande de tu DNI.

2) Una matriz de tamaño $m\times n$, donde $m$ es el dígito más pequeño (excluido el $0$) de tu DNI, y $n$ el dígito más grande, cuyas entradas sean todo cero.

3) Un vector cuyo primer elemento sea el dígito más pequeño de tu DNI, cuyo último elemento sea el dígito más grande, y que contenga $5$ elementos equiespaciados.

4) Un vector cuyo primer elemento sea el dígito más pequeño de tu DNI, el último el dígito más grande y donde cada elemento del array esté separado del siguiente en una unidad. 

In [3]:
# Completar aquí
#1.
U = np.ones([9, 9])
print(f"U = \n {U}")

#2
C = np.zeros([2, 9])
print(f"C = \n {C}")

#3
v = np.linspace(2, 9, 5)
print(f"El vector v es {v}")

#4
w = np.arange(2, 10, 1)
print(f"El vector w es {w}")
# --------------------


U = 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
C = 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
El vector v es [2.   3.75 5.5  7.25 9.  ]
El vector w es [2 3 4 5 6 7 8 9]


Apila de manera horizontal los vectores introducidos en los apartados 3) y 4) del apartado anterior.

Calcula el tamaño el array resultante.

In [8]:
# Completar aquí
apilar_horiz = np.hstack((v, w))
print(apilar_horiz)
print(f"El tamaño es {apilar_horiz.size}")
# --------------------


[2.   3.75 5.5  7.25 9.   2.   3.   4.   5.   6.   7.   8.   9.  ]
El tamaño es 13



Utiliza **vstack** para generar una matriz con dos filas, cada una de las cuales contenga al vector gnerado en el apartado 4) anterior.

Calcula el tipo o forma (shape) del array generado.

In [20]:
# Completar aquí
W = np.vstack((w, w))
print(W)
print(f"Tiene dimensión {W.shape}")
# --------------------


[[2 3 4 5 6 7 8]
 [2 3 4 5 6 7 8]]
Tiene dimensión (2, 7)


Intenta apilar, también de manera vertical, los vectores de los apartados 3) y 4) anteriores. 

Obtienes un error. ¿A qué se debe este error?

In [5]:
# Completar aquí
v_apilados = np.vstack((v, w))


#El error se debe a que al intentar apilar los vectores, estos no tienen el mismo número de columnas.
#En el ejercicio anterior se puede ver que si se apila, ya que tiene el mismo número de columnas
# --------------------


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 8

Introduce tu DNI en formato lita y tupla. Convierte ambos a formato **ndarray** 

In [6]:
# Completar aquí
lista = [2, 3, 4, 5, 6, 7, 8 , 9]
print(f"lista = {lista}")
print(type(lista))
array1 = np.array(lista)
print(f"El array de la lista = {array1}")
print(type(array1))

tupla = (2, 3, 4, 5, 6, 7, 8, 9)
print(f"tupla = {tupla}")
print(type(tupla))
array2 = np.array(tupla)
print(f"El array de la tupla = {array2}")
print(type(array2))
# --------------------


lista = [2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
El array de la lista = [2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
tupla = (2, 3, 4, 5, 6, 7, 8, 9)
<class 'tuple'>
El array de la tupla = [2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
