# Práctica 4: Ejercicio para entregar. 
## Vectores Y Matrices: aritmética y normas.



Los vectores y matrices de números complejos aparecen frecuentemente en Machine Learning. En concreto, en sistemas de reconocimiento del hablante (speech recognition) y más específicamente en la primera fase, donde se hace uso de una técnica de tratamiento de señales llamada **transformada discreta de Fourier**. En este ejercicio prácticaremos un poco con el tipo de vectores que aparecen en este campo.

Consideremos la llamada **matriz de la transformada de Fourier Discreta** en dimensión 4:
$$
DFT = \frac{1}{2}\left[\begin{array}{cccc}
1 & 1 & 1 & 1\\
1 & e^{2\pi j / 4} & e^{4\pi j / 4} & e^{6\pi j / 4}\\
1 & e^{4\pi j / 4} & e^{6\pi j / 4} & e^{8\pi j / 4}\\
1 & e^{6\pi j / 6} & e^{8\pi j / 8} & e^{10\pi j / 4}
\end{array}
\right]
$$
Nótese que las entradas de esta matriz tienen la forma $e^{2 k n \pi j/N}$, con  $n=0,1,2,3$, $N=4$ y $k = n^T$.

Introduce esta matriz siguiendo los siguiente pasos:

1) Introduce el escalar $N = 4$

2) Genera el vector $n = [0, 1, 2, 3]$ usando el método **arange**

3) Genera el vector $k = n^T$ usando el método **reshape**

4) Genera la matriz $n*k$

5) Genera la matriz con entradas $exp(2j * \pi * k * n / N)$



In [3]:
# Completar aquí
import numpy as np

N = 4
n = np.arange(4)
k = n.reshape((4, 1))
print(f"n = {n}")
print(f"k = {k}")
nk = n * k
print(f"nk = \n {nk}")
DFT = np.exp(2j * np.pi * k * n / N)
print(f"DFT = \n {DFT}")
print(f"Shape of DFT = {np.shape(DFT)}")
# --------------------


n = [0 1 2 3]
k = [[0]
 [1]
 [2]
 [3]]
nk = 
 [[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
DFT = 
 [[ 1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j
   1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17+1.0000000e+00j
  -1.0000000e+00+1.2246468e-16j -1.8369702e-16-1.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j -1.0000000e+00+1.2246468e-16j
   1.0000000e+00-2.4492936e-16j -1.0000000e+00+3.6739404e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16-1.0000000e+00j
  -1.0000000e+00+3.6739404e-16j  5.5109106e-16+1.0000000e+00j]]
Shape of DFT = (4, 4)


Utiliza la técnica de **slicing** estudiada en la práctica anterior para extraer la primer fila (que guardaremos en un vector denotado $v1$) y la tercera columna de la matriz $DFT$ (guardada en $v2$)


In [4]:
# Completar aquí
v1 = DFT[0, :]
print(f"v1 = {v1}")
v2 = DFT[:, 2]
print(f"v2 = {v2}")
# --------------------


v1 = [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
v2 = [ 1.+0.0000000e+00j -1.+1.2246468e-16j  1.-2.4492936e-16j
 -1.+3.6739404e-16j]


 Calcula:

 1) $v1 + v2$

 2) $v1*v2$, componente a componente

 3) $v1 / v2$, componente a componente

 4) El producto escalar de $v1$ y $v2$

In [5]:
# Completar aquí
print(f"La suma de v1 y v2 es: {v1 + v2}")
print(f"La multiplicación componente a componente de v1 y v2 es: {v1 * v2}")
print(f"La división componente a componente de v1 y v2 es: {v1 / v2}")
print(f"El producto escalar de v1 y v2 es: {v1.dot(v2)}")
# --------------------


La suma de v1 y v2 es: [2.+0.0000000e+00j 0.+1.2246468e-16j 2.-2.4492936e-16j 0.+3.6739404e-16j]
La multiplicación componente a componente de v1 y v2 es: [ 1.+0.0000000e+00j -1.+1.2246468e-16j  1.-2.4492936e-16j
 -1.+3.6739404e-16j]
La división componente a componente de v1 y v2 es: [ 1.+0.0000000e+00j -1.-1.2246468e-16j  1.+2.4492936e-16j
 -1.-3.6739404e-16j]
El producto escalar de v1 y v2 es: 2.449293598294706e-16j


Calcula las normas $2$, $1$ y $\infty$ de $v1$

In [6]:
# Completar aquí
l2 = np.linalg.norm(v1, 2)
l1 = np.linalg.norm(v1, 1)
linf = np.linalg.norm(v1, np.inf)
print(f"La norma 2 de v1 es: {l2}")
print(f"La norma 1 de v1 es: {l1}")
print(f"La norma infinita de v1 es: {linf}")
# --------------------


La norma 2 de v1 es: 2.0
La norma 1 de v1 es: 4.0
La norma infinita de v1 es: 1.0


Introduce una matriz D de 4 filas y 8 columnas de modo que la primera fila 
contenga tu número de DNI y el resto de filas números de DNI de algunos 
familiares tuyos.
Imprime también por pantalla la matriz D

In [7]:
# Completar aquí
D = np.array([[2, 9, 5, 2, 9, 0, 7, 9],
              [1, 3, 4, 9, 0, 4, 2, 2],
              [7, 6, 5, 3, 0, 0, 2, 4],
              [0, 1, 6, 5, 9, 9, 0, 1]])
print(f"La matriz D: \n {D}")
# --------------------


La matriz D: 
 [[2 9 5 2 9 0 7 9]
 [1 3 4 9 0 4 2 2]
 [7 6 5 3 0 0 2 4]
 [0 1 6 5 9 9 0 1]]


Calcula, usando las dos formas estudiadas en clase, e imprime por pantalla 
la matriz S = DD^T

In [8]:
# Completar aquí
S = D.dot(D.T)
print(f"S = DD^T: \n {S}")
S = (D @ D.T)
print(f"S = DD^T: \n {S}")
# --------------------


S = DD^T: 
 [[325  99 149 139]
 [ 99 131  84 110]
 [149  84 139  55]
 [139 110  55 225]]
S = DD^T: 
 [[325  99 149 139]
 [ 99 131  84 110]
 [149  84 139  55]
 [139 110  55 225]]


Introduce un vector b no nulo de dimensión 4, el que quieras, y calcula, de las 
dos formas que vimos en clase, el producto de S y b, es decir, S*b.
Calcula también b*S. Compara los resultados de S*b y b*S. 
¿Qué explicación encuentras de ambos resultados? 

In [9]:
# Completar aquí
b = np.array([1, 3, 5, 6])
print(np.shape(b))
print(f"S.b = {S.dot(b)}")
print(f"S.b = {S @ b}")
print(f"b.S = {b.dot(S)}")
print(f"b.S = {b @ S}")

"""Python interpreta el vector, según sea necesario(fila o columna),a no ser que hagas un reshape y le indiques a Python la dirección.
En cuanto a que los dos vecotres sean iguales, es por que la matriz es simétrica y la traspuesta igual. """
# --------------------


(4,)
S.b = [2201 1572 1426 2094]
S.b = [2201 1572 1426 2094]
b.S = [2201 1572 1426 2094]
b.S = [2201 1572 1426 2094]


'Python interpreta el vector, según sea necesario(fila o columna),a no ser que hagas un reshape y le indiques a Python la dirección.\nEn cuanto a que los dos vecotres sean iguales, es por que la matriz es simétrica y la traspuesta igual. '

Calcula el producto de Hadamard de S y S. 
Calcula, componente a componente de S dividido por S.

In [10]:
# Completar aquí
print(f"Producto de Hadamard: {S * S}")
print(f"La división componente a componente es: {S / S}")
# --------------------


Producto de Hadamard: [[105625   9801  22201  19321]
 [  9801  17161   7056  12100]
 [ 22201   7056  19321   3025]
 [ 19321  12100   3025  50625]]
La división componente a componente es: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Comprueba que S es simétrica utilizando un operador Booleano

In [11]:
# Completar aquí
S == S.T
# --------------------


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Calcula la inversa de S, su traza, su determinante y su rango,

In [12]:
# Completar aquí
B = np.linalg.inv(S)  ## Inversa
print(f"La inversa de A = \n {B}")
print(f"Comprobación: \n {S @ B}")

print(f"La traza de A = {np.trace(S)}") ##Traza

print(f"El determinante de A = {np.linalg.det(S)}") ##Determinante

print(f"El rango de A = {np.linalg.matrix_rank(S)}")  ##Rango
# --------------------


La inversa de A = 
 [[ 0.00800491  0.00332345 -0.00884508 -0.00440793]
 [ 0.00332345  0.0208942  -0.01254872 -0.00920063]
 [-0.00884508 -0.01254872  0.02177564  0.00627629]
 [-0.00440793 -0.00920063  0.00627629  0.01013144]]
Comprobación: 
 [[ 1.00000000e+00  1.37043155e-16 -3.52148866e-16 -7.30318583e-16]
 [-7.45931095e-17  1.00000000e+00 -4.12864187e-16  2.42861287e-17]
 [ 1.56992475e-16 -2.02962647e-16  1.00000000e+00  1.21430643e-17]
 [ 1.64798730e-17 -1.43982049e-16 -3.90312782e-16  1.00000000e+00]]
La traza de A = 820
El determinante de A = 180845181.99999997
El rango de A = 4


## Ejercicio para hacer a mano

 Sean $u,v$ dos vectores no nulos vistos como matrices columna $n\times 1$. Observa que $1+v^{\top}u$ es un escalar, que suponemos no nulo. Prueba que la matriz $A = I+uv^{\top}$ es no singular y su inversa es
$$A^{-1}=I-\dfrac{uv^{\top}}{1+v^{\top}u}$$

Elige dos vectores $u= [1, 2, 3]$ y $v=[4, 5, 6]$ de $\mathbb{R}^3$ y comprueba en Python (no hace falta que lo hagas a mano) que se cumple la identidad anterior

In [13]:
# Completar aquí
u = np.array([1, 2, 3]).reshape((3, 1))
v = np.array([4, 5, 6]).reshape((3, 1))
I = np.identity(3)
print(I)
A = I + (u.dot(v.T))
print(A)
B = I - (u.dot(v.T) / (1 + (v.T).dot(u)))
print(B)
print(A.dot(B))
# --------------------


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 5.  5.  6.]
 [ 8. 11. 12.]
 [12. 15. 19.]]
[[ 0.87878788 -0.15151515 -0.18181818]
 [-0.24242424  0.6969697  -0.36363636]
 [-0.36363636 -0.45454545  0.45454545]]
[[ 1.00000000e+00  3.33066907e-16  0.00000000e+00]
 [-4.44089210e-16  1.00000000e+00  0.00000000e+00]
 [-9.99200722e-16  6.10622664e-16  1.00000000e+00]]
