# Práctica 10: Ejercicio para entregar. 
## Autovalores y autovectores en Python


Algunos problemas en Data Science requieren el cálculo de valor propio dominante (el más grande) de una matriz. 

En este ejercicio implementaremos el llamado **Método de la Potencia** para el cálculo de dicho valor propio dominante. Aplicaremos dicho método a una **matriz de Markov** y compararemos los resultados obtenidos con el método **eig** implementado por defecto en Python.



Partimos de una matriz $M$. En este caso, una matriz cuadrada cuyas entradas son positivas y de modo que, para cada columna, si sumamos sus entradas, el resultado es $1$. Este tipo de matrices se llaman de **Markov** y tienen aplicaciones en Álgebra Lineal, Estadística e Informática. Por ejemplo, la siguiente matriz de orde $2$ es de Markov:

$$
M_2 = \left[
    \begin{array}{cc}
    0.2 & 0.4 \\ 
    0.8 & 0.6 \\
    \end{array}
    \right]
$$



Introduce una matriz de Markov de orden $4$, la que tú quieras, y denótala por $M$.

In [129]:
# Completar aquí
import numpy as np
M = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.2, 0.3, 0.4, 0.5],
    [0.4, 0.3, 0.2, 0.1],
    [0.3, 0.2, 0.1, 0.]
])
print(f"M = \n {M}")
# --------------------


M = 
 [[0.1 0.2 0.3 0.4]
 [0.2 0.3 0.4 0.5]
 [0.4 0.3 0.2 0.1]
 [0.3 0.2 0.1 0. ]]


El método de la potencia es un método iterativo donde se parte incialmente de un vector (el llamado **initial guess**). 

Introducimos un vector (1d-array) con cuatro componentes, por ejemplo $v = (0.5, 0.5, 0.5, 0.5)$.

In [130]:
# Completar aquí
v = np.array([0.5, 0.5, 0.5, 0.5])
print(f"v = {v}")
# --------------------


v = [0.5 0.5 0.5 0.5]


A continuación vamos a implementar un bucle (loop) con $11$ iteraciones donde en cada iteración vamos a hacer lo siguiente:

1) Multiplicamos $M$ y $v$ y volvemos a denotar por $v$ el resultado, es decir,
**v = M v**.

2) Calculamos la mayor, en valor absoluto, de las componentes de **v**. Recuerda, el valor absoluto de un vector se calcula con **abs** y el máximo aplicando el método **max()**. Denotamos por **lambda** al resultado. Esto nos da una aproximación del valor propio dominante.

3) Dividimos **v** por la mayor de sus componentes. Esto nos da una aproximación del vector propio asociado al valor propio dominante

4) Imprimimos los resultados de 2) y 3) en cada iteración.

In [131]:
# Completar aquíl
# Bucle de 11 iteraciones
for i in range(11):
    v = np.dot(M, v)
    lamda = max(abs(v))
    print(f"  Valor propio dominante en la iteración {i} = {lamda}")
    vector_propio = v / lamda
    v = vector_propio
    print(f"  Vector propio asociado en la iteración {i} = {vector_propio}")
# --------------------


  Valor propio dominante en la iteración 0 = 0.7000000000000001
  Vector propio asociado en la iteración 0 = [0.71428571 1.         0.71428571 0.42857143]
  Valor propio dominante en la iteración 1 = 0.9428571428571428
  Vector propio asociado en la iteración 1 = [0.6969697  1.         0.81818182 0.51515152]
  Valor propio dominante en la iteración 2 = 1.0242424242424244
  Vector propio asociado en la iteración 2 = [0.70414201 1.         0.77514793 0.47928994]
  Valor propio dominante en la iteración 3 = 0.9905325443786981
  Vector propio asociado en la iteración 3 = [0.70131422 1.         0.7921147  0.49342891]
  Valor propio dominante en la iteración 4 = 1.0038231780167264
  Vector propio asociado en la iteración 4 = [0.7024518  1.         0.78528922 0.48774101]
  Valor propio dominante en la iteración 5 = 0.9984765532016188
  Vector propio asociado en la iteración 5 = [0.70199781 1.         0.78801316 0.49001097]
  Valor propio dominante en la iteración 6 = 1.0006103084918705
  Vect

Comprueba que, en efecto, se cumple que $M v = \lambda v$, para $\lambda$ el autovalor dominante que acabas de calcular y $v$ su autovector asociado. 

In [132]:
# Completar aquí
x = M.dot(v)
y = lamda * v
print(x)
print(y)

# --------------------


[0.70212274 0.99999375 0.78723231 0.4893613 ]
[0.70213995 1.00001562 0.78723836 0.4893627 ]


Comparamos ahora los resultados obtenidos con los que provienen del método **eig** implementado en el submódulo **np.linalg** de Python



In [133]:
# Completar aquí
from numpy.linalg import eig
autovalores, autovectores = eig(M)
print(f"Autovalores = {autovalores}")
print(f"Autovectores = \n {autovectores}")
# --------------------


Autovalores = [ 1.00000000e+00 -4.00000000e-01  1.95342192e-17 -1.35009044e-16]
Autovectores = 
 [[-0.45780377  0.5         0.15138727  0.54016032]
 [-0.65202356  0.5         0.19049503 -0.78781894]
 [-0.51329514 -0.5        -0.83515188 -0.04484309]
 [-0.31907536 -0.5         0.49326958  0.29250171]]


Identificamos el valor propio dominante con valor $\lambda_{max} = 1$. Pero los autovectores, ¿dónde están? ¿dónde está el vector propio asociado a $\lambda_{max}$?

Una pista: investiga la primera columna de la salida anterior.

In [134]:
# Completar aquí
proporcion = (v / autovectores[:, 0])
print(f"Proporcionalidad: {proporcion}")


x = M.dot(autovectores[:, 0])
y = autovalores[0] * autovectores[:, 0]
print(f"M * autovector dominante = \n {x}")
print(f"Autovalor dominante * autovector dominante = \n {y}")
print("Ambos vectores son iguales")


"""El vector asociado al valor propio dominante es el vector de la primera 
columna de la matriz de autovectores del método eig(). Si comparamos el vector 
propio dominante del método de la potencia con el correspondiente al valor propio dominante
nos sale que son proporcionales"""
# --------------------


Proporcionalidad: [-1.53368982 -1.53368692 -1.53367138 -1.53366609]
M * autovector dominante = 
 [-0.45780377 -0.65202356 -0.51329514 -0.31907536]
Autovalor dominante * autovector dominante = 
 [-0.45780377 -0.65202356 -0.51329514 -0.31907536]
Ambos vectores son iguales


'El vector asociado al valor propio dominante es el vector de la primera \ncolumna de la matriz de autovectores del método eig(). Si comparamos el vector \npropio dominante del método de la potencia con el correspondiente al valor propio dominante\nnos sale que son proporcionales'