# Práctica 3: Ejercicio para entregar. 
## NumPy arrays: index, slice, reshape, broadcasting, etc.



Introduce tu DNI en la forma de 1d-array.

A continuación, selecciona e imprime la siguiente información de dicho array:

1) el primer elemento
2) el último
3) El que ocupa la segunda posición (empezando desde la izquierda)
4) el que ocupa la antepenúltima 
5) los tres primeros elementos
6) los 4 últimos elementos

In [13]:
import numpy as np

In [14]:
# Completar aquí
dni = np.array([2, 9, 5, 2, 9, 0, 7, 9])
print(dni)
print(f"El primer elemento es {dni[0]}")
print(f"El último elemento es {dni[-1]}")
print(f"El segundo elemnto es {dni[1]}")
print(f"El antepenúltimo elemento es {dni[-3]}")
print(f"Los tres primeros elementos son {dni[:3]}")
print(f"Los cuatro últimos elementos son {dni[-4:]}")
# --------------------


[2 9 5 2 9 0 7 9]
El primer elemento es 2
El último elemento es 9
El segundo elemnto es 9
El antepenúltimo elemento es 0
Los tres primeros elementos son [2 9 5]
Los cuatro últimos elementos son [9 0 7 9]


Cambia la forma del 1d-array que contiene tu nombre para convertirlo en un 2d-array (matriz) de tamaño $2\times 4$, es decir dos filas y cuatro columnas. 

A continuación, selecciona e imprime los siguientes datos del nuevo 2d-array:

1) la primera fila
2) la segunda columna

In [15]:
# Completar aquí
DNI = dni.reshape((2, 4))
print(DNI)
print(f"Primera fila = {DNI[0, :]}")
print(f"Segunda columna = {DNI[:, 1]}")
# --------------------


[[2 9 5 2]
 [9 0 7 9]]
Primera fila = [2 9 5 2]
Segunda columna = [9 0]


Imaginemos que el 2d-array del ejercicio anterior contiene las features $X$ y las labels $y$ de un modelo de Machine Learning. En concreto, $X$ almacena todos los datos excepto la última columna mientras que $y$ contiene los datos de la última columna.

Genera $X$ e $y$.

In [16]:
# Completar aquí
X, y = DNI[:, :3], DNI[:, -1]
print(f"X = \n {X}")
print(f"y = \n {y}")

# --------------------


X = 
 [[2 9 5]
 [9 0 7]]
y = 
 [2 9]


Supongamos ahora que queremos separar los datos del 2d-array en dos subconjuntos, un training dataset y un test dataset.

Training dataset será la primera fila y  test dataset será la segunda fila

In [17]:
# Completar aquí
print(f"Training dataset = {DNI[0, :]}")
print(f"Test dataset = {DNI[1, :]}")
# --------------------


Training dataset = [2 9 5 2]
Test dataset = [9 0 7 9]


Introduce un escalar que se corresponda con tu nota de entrada al grado de Ciencia e Ingeniería de Datos. A continuación realiza las siguientes operaciones:

1) Suma el escalar al 2d-array anterior
2) Multiplica el escalar al 2d-array anterior
3) Divide el 2d-array por el escalar

In [19]:
# Completar aquí
escalar = 11
print(f"{DNI}")
print(f"Suma del escalar al 2d-array anterior = \n {DNI + escalar}")
print(f"Multiplicación del escalar al 2d-array anterior = \n {DNI * 11}")
print(f"División del 2d-array por el escalar = \n {DNI/11}")
# --------------------


[[2 9 5 2]
 [9 0 7 9]]
Suma del escalar al 2d-array anterior = 
 [[13 20 16 13]
 [20 11 18 20]]
Multiplicación del escalar al 2d-array anterior = 
 [[22 99 55 22]
 [99  0 77 99]]
División del 2d-array por el escalar = 
 [[0.18181818 0.81818182 0.45454545 0.18181818]
 [0.81818182 0.         0.63636364 0.81818182]]
