In [1]:
import numpy as np

Ejercicio 1

In [6]:
from scipy.sparse import csr_matrix
row = np.array([0, 1, 2, 3, 3, 3])
col = np.array([0, 1, 2, 2, 1, 0])
data = np.array([1, 1, 1, 1, 1, 1])

M_sparse = csr_matrix((data, (row, col)), shape=(4, 4))
M_dense = M_sparse.todense()

print(f"Matriz Z en formato sparse = \n {M_sparse}") 
print(f"Matriz Z en formato dense = \n {M_dense}")

Matriz Z en formato sparse = 
   (np.int32(0), np.int32(0))	1
  (np.int32(1), np.int32(1))	1
  (np.int32(2), np.int32(2))	1
  (np.int32(3), np.int32(0))	1
  (np.int32(3), np.int32(1))	1
  (np.int32(3), np.int32(2))	1
Matriz Z en formato dense = 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 1 1 0]]


In [99]:
from scipy.linalg import svd

M = M_dense
U, s, V = svd(M)

Sigma = np.zeros((M.shape[0], M.shape[1]))

Sigma[:M.shape[0], :M.shape[1]] = np.diag(s)

print(f"U = \n {U}")
print(f"Sigma = \n {Sigma}")
print(f"V^T = {V}")

U = 
 [[-2.88675135e-01  8.16496581e-01  7.85046229e-17 -5.00000000e-01]
 [-2.88675135e-01 -4.08248290e-01  7.07106781e-01 -5.00000000e-01]
 [-2.88675135e-01 -4.08248290e-01 -7.07106781e-01 -5.00000000e-01]
 [-8.66025404e-01  0.00000000e+00 -7.85046229e-17  5.00000000e-01]]
Sigma = 
 [[2. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
V^T = [[-0.57735027 -0.57735027 -0.57735027 -0.        ]
 [ 0.81649658 -0.40824829 -0.40824829  0.        ]
 [-0.          0.70710678 -0.70710678 -0.        ]
 [ 0.          0.          0.          1.        ]]


In [26]:
u_1 = U[:, 0]
u_2 = U[:, 1]
u_3 = U[:, 2]
u_4 = U[:, 3]
print(f"La norma euclídea del vector columna u_1 = {np.linalg.norm(u_1, 2)}")
print(f"La norma euclídea del vector columna u_2 = {np.linalg.norm(u_2, 2)}")
print(f"La norma euclídea del vector columna u_3 = {np.linalg.norm(u_3, 2)}")
print(f"La norma euclídea del vector columna u_4 = {np.linalg.norm(u_4, 2)}")
print(f"El producto escalar del vector columa u_1 y u_2 = {u_1 @ u_2}")
print(f"El producto escalar del vector columa u_1 y u_3 = {u_1 @ u_3}")
print(f"El producto escalar del vector columa u_1 y u_4 = {u_1 @ u_4}")
print(f"El producto escalar del vector columa u_2 y u_3 = {u_2 @ u_3}")
print(f"El producto escalar del vector columa u_2 y u_4 = {u_2 @ u_4}")
print(f"El producto escalar del vector columa u_3 y u_4 = {u_3 @ u_4}")

V_inv = np.linalg.inv(V)
V_T = V.T

print(f"V^T == V^-1 ? {np.allclose(V_inv, V_T)}")

La norma euclídea del vector columna u_1 = 0.9999999999999999
La norma euclídea del vector columna u_2 = 0.9999999999999996
La norma euclídea del vector columna u_3 = 1.0
La norma euclídea del vector columna u_4 = 0.9999999999999999
El producto escalar del vector columa u_1 y u_2 = 6.938893903907228e-17
El producto escalar del vector columa u_1 y u_3 = 6.798699777552591e-17
El producto escalar del vector columa u_1 y u_4 = 0.0
El producto escalar del vector columa u_2 y u_3 = 1.6653345369377348e-16
El producto escalar del vector columa u_2 y u_4 = 8.326672684688674e-17
El producto escalar del vector columa u_3 y u_4 = 1.6258839764163454e-17
V^T == V^-1 ? True


In [88]:
r = np.linalg.matrix_rank(M)
print(f"El rango de M = {r}")
U_r = U[:, :r]

Sigma_r = Sigma[:r, :r]

V_r = V[:r, :]
print(f"U_r = {U_r}")
print(f"Sigma_r = {Sigma_r}")
print(f"V_r = {V_r}")
print(np.allclose(M, U_r @ Sigma_r @ V_r))
u_1 = U_r[:, 0]
u_2 = U_r[:, 1]
u_3 = U_r[:, 2]
v_1 = V_r[0, :]
v_2 = V_r[1, :]
v_3 = V_r[2, :]

print(f"Descomposicion espectral = {Sigma_r[0,0]} * {(u_1.reshape(4, 1) @ v_1.reshape(1, 4))} \n + {Sigma_r[1,1]} * {(u_2.reshape(4, 1) @ v_2.reshape(1, 4))} \n + {Sigma_r[2,2]} * {(u_3.reshape(4, 1) @ v_3.reshape(1, 4))}")

El rango de M = 3
U_r = [[-2.88675135e-01  8.16496581e-01  7.85046229e-17]
 [-2.88675135e-01 -4.08248290e-01  7.07106781e-01]
 [-2.88675135e-01 -4.08248290e-01 -7.07106781e-01]
 [-8.66025404e-01  0.00000000e+00 -7.85046229e-17]]
Sigma_r = [[2. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
V_r = [[-0.57735027 -0.57735027 -0.57735027 -0.        ]
 [ 0.81649658 -0.40824829 -0.40824829  0.        ]
 [-0.          0.70710678 -0.70710678 -0.        ]]
True
Descomposicion espectral = 2.0 * [[0.16666667 0.16666667 0.16666667 0.        ]
 [0.16666667 0.16666667 0.16666667 0.        ]
 [0.16666667 0.16666667 0.16666667 0.        ]
 [0.5        0.5        0.5        0.        ]] 
 + 1.0 * [[ 0.66666667 -0.33333333 -0.33333333  0.        ]
 [-0.33333333  0.16666667  0.16666667  0.        ]
 [-0.33333333  0.16666667  0.16666667  0.        ]
 [ 0.          0.          0.          0.        ]] 
 + 0.9999999999999999 * [[ 0.00000000e+00  5.55111512e-17 -5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00  5.00000000e

In [101]:
Mb = np.array([
    [1, 0, 0, 0, 1], 
    [0, 1, 0, 0, 1],
    [0, 0, 1, 0, 1],
    [1, 1, 1, 0, 1]
])

print(f"Ab = \n {Mb}")
print(f"rango de A = {np.linalg.matrix_rank(M)}")
print(f"rango de la matriz ampliada = {np.linalg.matrix_rank(Mb)}")

# El sistema no tiene solución ya que el rg(A) y rg(Ab) son distintos, por lo que el sistema es incompatible


Ab = 
 [[1 0 0 0 1]
 [0 1 0 0 1]
 [0 0 1 0 1]
 [1 1 1 0 1]]
rango de A = 3
rango de la matriz ampliada = 4


In [105]:
#Cuando realiamos la factorizacion SVD, el subspacio Col(A), se encuentra en u_1, u_2, ... , u_r por
#lo que aquí nustra matriz a seria [u_1, u_2, u_3] = U_r
A = U_r
b = np.array([1, 1, 1, 1])
x = (np.linalg.inv(A.T @ A))@ A.T @ b
print(f"Base columna M = \n {A}")
print(x)
print(A @ x)



Base columna M = 
 [[-2.88675135e-01  8.16496581e-01  7.85046229e-17]
 [-2.88675135e-01 -4.08248290e-01  7.07106781e-01]
 [-2.88675135e-01 -4.08248290e-01 -7.07106781e-01]
 [-8.66025404e-01  0.00000000e+00 -7.85046229e-17]]
[-1.73205081e+00 -1.11022302e-16  1.11022302e-16]
[0.5 0.5 0.5 1.5]


In [16]:
num = 0
i = 1
while num < 100:
    if i % 4 == 0:
        print(i)
        num = num + 1
    i = i + 1


4
8
12
16
20
24
28
32
36
40
44
48
52
56
60
64
68
72
76
80
84
88
92
96
100
104
108
112
116
120
124
128
132
136
140
144
148
152
156
160
164
168
172
176
180
184
188
192
196
200
204
208
212
216
220
224
228
232
236
240
244
248
252
256
260
264
268
272
276
280
284
288
292
296
300
304
308
312
316
320
324
328
332
336
340
344
348
352
356
360
364
368
372
376
380
384
388
392
396
400
