## Práctica 4: Repasar vectores y matrices: aritmética y normas.

### Vectores

In [1]:
import numpy as np

In [9]:
v = np.array([1, 2, 3])
print(f"v = {v}")

u = np.array([1, 2, 3])
print(f"u = {u}")

#Suma y resta de vectores
print(f"v + u = {v + u}")
print(f"v - u = {v - u}")

#Producto y cociente componente a componente
print(f"u * v = {u * v}")
print(f"u / v = {u / v}")

v = [1 2 3]
u = [1 2 3]
v + u = [2 4 6]
v - u = [0 0 0]
u * v = [1 4 9]
u / v = [1. 1. 1.]


In [11]:
#Escalar por un vector
a = 2.0
print(f"a * v = {a * v}")

a * v = [2. 4. 6.]


In [12]:
#Producto escalar
print(f"u.v = {u.dot(v)}")

u.v = 14


In [18]:
#Normas de vectores
l2 = np.linalg.norm(u, 2)
print(f"La norma 2 de u = {l2}")

l1 = np.linalg.norm(u, 1)
print(f"La norma 2 de u = {l1}")

lmax = np.linalg.norm(u, np.inf)
print(f"La norma 2 de u = {lmax}")



La norma 2 de u = 3.7416573867739413
La norma 2 de u = 6.0
La norma 2 de u = 3.0


### Matrices

In [30]:
A = np.array([
    [1, 3, 5],
    [7, 9, 11]
])
print(f"A = \n {A}")

B = np.array([
    [0, 2, 4],
    [6, 8, 10]
])
print(f"B = \n {B}")

#Suma y resta de matrices
print(f"A + B = \n {A + B}")
print(f"A - B = \n {A - B}")

#Producto de Hadamard (componente a componente), con el mismo tamaño
print(f"A * B = \n {A * B}")
print(f"A / B = \n {B / A}")

print(f"A.B = \n {A.dot(B)}")



A = 
 [[ 1  3  5]
 [ 7  9 11]]
B = 
 [[ 0  2  4]
 [ 6  8 10]]
A + B = 
 [[ 1  5  9]
 [13 17 21]]
A - B = 
 [[1 1 1]
 [1 1 1]]
A * B = 
 [[  0   6  20]
 [ 42  72 110]]
A / B = 
 [[0.         0.66666667 0.8       ]
 [0.85714286 0.88888889 0.90909091]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [34]:
#Producto de matrices

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = np.array([
    [1, 2],
    [3, 4]
])

print(f"A.B = \n {A.dot(B)}") #Producto usual
print(f"A.B = \n {A @ B}") #Otra forma


A.B = 
 [[ 7 10]
 [15 22]
 [23 34]]
A.B = 
 [[ 7 10]
 [15 22]
 [23 34]]


In [38]:
#Producto matriz por vector
b = np.array([0.5, 0.5]) #EL vector es vertical
print(b)
print(A)
print(f"A.b = {A.dot(b)}")

[0.5 0.5]
[[1 2]
 [3 4]
 [5 6]]
A.b = [1.5 3.5 5.5]


In [39]:
b = 0.5
print(f"b * A = \n {b * A}")

b * A = 
 [[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


In [45]:
#Algunos tipos de matrices
A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
])
print(f"A = \n {A}")

print(f"A^T = \n {A.T}")
# ¿Es A Simétrica?
A == A.T


A = 
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
A^T = 
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [48]:
#Matrices diagonales
d = np.diag(A)
print(f"La diagonal de A = \n {d}")

D = np.diag(d)
print(f"D = \n {D}")

La diagonal de A = 
 [2 2 2]
D = 
 [[2 0 0]
 [0 2 0]
 [0 0 2]]


In [53]:
#Matriz identidad
I = np.identity(4)
print(f"I = \n {I}")

I = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [64]:
#Inversa, traza, determinante y rango de una matriz
B = np.linalg.inv(A)  ## Inversa
print(f"La inversa de A = \n {B}")
print(f"A.B = \n {B @ A}")


print(f"La traza de A = {np.trace(A)}") ##Traza

print(f"El determinante de A = {np.linalg.det(A)}") ##Determinante

print(f"El rango de A = {np.linalg.matrix_rank(A)}")  ##Rango

La inversa de A = 
 [[0.75 0.5  0.25]
 [0.5  1.   0.5 ]
 [0.25 0.5  0.75]]
A.B = 
 [[ 1.00000000e+00  5.55111512e-17 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00 -1.11022302e-16  1.00000000e+00]]
La traza de A = 6
El determinante de A = 4.0
El rango de A = 3
