# Práctica 7: Factorizaciones LU. PLU y Cholesky.
### Métodos directos de resolución de sistemas lineales

### Factorizaciones LU y PLU

In [1]:
import numpy as np

In [4]:
A = np.array([
    [4, -3, -5],
    [-2, -4, 5],
    [8, 8, 0]
])
print(f"A = \n {A}")

A = 
 [[ 4 -3 -5]
 [-2 -4  5]
 [ 8  8  0]]


In [8]:
from scipy.linalg import lu

In [9]:
P , L , U = lu(A)
print(f"P = \n {P}")
print(f"L = \n {L}")
print(f"U = \n {U}")

P = 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L = 
 [[ 1.          0.          0.        ]
 [ 0.5         1.          0.        ]
 [-0.25        0.28571429  1.        ]]
U = 
 [[ 8.          8.          0.        ]
 [ 0.         -7.         -5.        ]
 [ 0.          0.          6.42857143]]


In [11]:
print(f"LU = \n {np.dot(L, U)}")
LU = np.dot(L, U) 
print(f"PLU = \n {np.dot(P, LU)}")

LU = 
 [[ 8.  8.  0.]
 [ 4. -3. -5.]
 [-2. -4.  5.]]
PLU = 
 [[ 4. -3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


### Facotrizacion de Choelsky

In [ ]:
T = np.array([
    [],
    [],
    []
])