### Práctica 9: Factorización QR y cáculo de valores y vectores propios

In [1]:
import numpy as np

#### Factorización QR

In [13]:
np.random.seed(42)
A = np.random.randn(4, 4)
print(F"A = \n {A}")

A = 
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]]


In [14]:
Q, R = np.linalg.qr(A)
print(f"Q = \n {Q}")
print(f"R = \n {R}")

Q = 
 [[-0.65193405  0.27665475  0.24146099 -0.66343103]
 [ 0.30732476 -0.30022049  0.89738645 -0.1005818 ]
 [ 0.61618204 -0.02782107 -0.30180808 -0.72695087]
 [-0.31757389 -0.91244495 -0.21285213 -0.14589381]]
R = 
 [[-0.76190859  0.96010672  0.32532019 -0.86546981]
 [ 0.          1.76270954  1.29185941  0.71696733]
 [ 0.          0.          2.08057134  1.31668292]
 [ 0.          0.          0.         -0.66701831]]


In [17]:
# Q es ortogonal
np.allclose(Q.T, np.linalg.inv(Q))

True

In [18]:
# Comprobamos que A = QxR
np.allclose(A, Q.dot(R))

True

#### Cálculo de valores y vecotres propios

In [19]:
from numpy.linalg import eig

In [23]:
A = np.array([
    [1, 2, 3,],
    [4, 5, 6],
    [7, 8, 9]
])
autovalores, autovectores = eig(A)
print(f"Autovalores = {autovalores}")
print(f"Autovectores = \n {autovectores}")

Autovalores = [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Autovectores = 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [28]:
# Para el primer autovalor tenemos:
B = A.dot(autovectores[:,0]) #Multiplicamos por la primera columna
print(B)
C = autovectores[:, 0] * autovalores[0]
print(C)

#Para el segundo autovalor tenemos:
B = A.dot(autovectores[:,1]) #Multiplicamos por la segunda columna
print(B)
C = autovectores[:, 1] * autovalores[1]
print(C)

#Para el tercer autovalor tenemos:
B = A.dot(autovectores[:,2]) #Multiplicamos por la primera columna
print(B)
C = autovectores[:, 2] * autovalores[2]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]
[ 0.87764976  0.09688771 -0.68387434]
[ 0.87764976  0.09688771 -0.68387434]
[-9.43689571e-16 -9.99200722e-16 -1.66533454e-16]
[-5.32224203e-16  1.06444841e-15 -5.32224203e-16]


In [29]:
P = autovectores
D = np.diag(autovalores)
inv_P = np.linalg.inv(P)
print(f"PDP^{-1} = \n {P.dot(D).dot(inv_P)}")

PDP^-1 = 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


#### Algoritmo QR para el cáclculo de vectores y valores propios

In [34]:
from numpy.linalg import qr
A = np.array([
    [0, 2],
    [2, 3]
])

Q, R = qr(A)
print(f"Q = \n {Q}")
print(f"R = \n {R}")

Q = 
 [[ 0. -1.]
 [-1.  0.]]
R = 
 [[-2. -3.]
 [ 0. -2.]]


In [41]:
autovalores, autovectores = eig(A)
print(f"Autovalores = {autovalores}")
print(f"Autovectores = \n {autovectores}")

Autovalores = [ 4. -1.]
Autovectores = 
 [[1.00000000e+00 2.09031537e-17]
 [0.00000000e+00 1.00000000e+00]]


In [42]:
p = [1, 5, 10, 20, 40]

for i in range(40):
    Q, R = qr(A)
    A = np.dot(R, Q)
    if i + 1 in p:
        print(f"Iteración {i + 1}")
        print(f"A = \n {A}")
        print(f"Q = \n {Q}")

Iteración 1
A = 
 [[ 4.00000000e+00  1.04515768e-16]
 [ 1.17041909e-96 -1.00000000e+00]]
Q = 
 [[-1.00000000e+00 -1.17041909e-96]
 [-1.17041909e-96  1.00000000e+00]]
Iteración 5
A = 
 [[ 4.00000000e+00  1.04515768e-16]
 [ 4.57194957e-99 -1.00000000e+00]]
Q = 
 [[-1.00000000e+00 -4.57194957e-99]
 [-4.57194957e-99  1.00000000e+00]]
Iteración 10
A = 
 [[ 4.00000000e+000 -1.04515768e-016]
 [ 4.46479450e-102 -1.00000000e+000]]
Q = 
 [[-1.0000000e+000 -4.4647945e-102]
 [-4.4647945e-102  1.0000000e+000]]
Iteración 20
A = 
 [[ 4.00000000e+000 -1.04515768e-016]
 [ 4.25795984e-108 -1.00000000e+000]]
Q = 
 [[-1.00000000e+000 -4.25795984e-108]
 [-4.25795984e-108  1.00000000e+000]]
Iteración 40
A = 
 [[ 4.00000000e+000 -1.04515768e-016]
 [ 3.87259191e-120 -1.00000000e+000]]
Q = 
 [[-1.00000000e+000 -3.87259191e-120]
 [-3.87259191e-120  1.00000000e+000]]
