# Práctica 

### Introducción a Numpy n-dimensional arrays

[N-dimensional array](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray)

In [2]:
import numpy as np

In [4]:
x = np.array([1 , 4, 3])
print(f"x = {x}")
print(type(x))
print(x.shape)
print(x.size)
print(x.dtype)

x = [1 4 3]
<class 'numpy.ndarray'>
(3,)
3
int64


In [7]:
A = np.array([[1, 4, 3],
             [9, 2, 7]])
print(f"A = \n {A}")
print(type(A))
print(A.shape)
print(A.size)
print(A.dtype)

A = 
 [[1 4 3]
 [9 2 7]]
<class 'numpy.ndarray'>
(2, 3)
6
int64


#### Algunos arrays destacados

In [8]:
A = np.zeros([3, 2])
print(f"A = \n {A}")

A = 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
c = np.arange(1, 5, 0.5)
print(c)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [11]:
array_complex = 1j * np.arange(5)
print(array_complex)

[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]


In [12]:
z = np.ones(4, dtype=complex) * 2
print(z)

[2.+0.j 2.+0.j 2.+0.j 2.+0.j]


In [13]:
d = np.linspace(0, 1, 10)
print(d)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Apilamiento de datos

In [17]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(a1)
print(a2)
a3 = np.vstack((a1, a2))
print(a3)
a4 = np.hstack((a1, a2))
print(a4)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Listas, tuplas y arrays de numpy

In [20]:
lista = [1, 2, 3]
print(lista)
print(type(lista))

vector = np.array(lista)
print(vector)
print(type(vector))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [23]:
data = [[11, 22],
        [33, 44],
        [55, 66]]
print(data)
print(type(data))

matriz = np.array(data)
print(data)
print(type(matriz))

[[11, 22], [33, 44], [55, 66]]
<class 'list'>
[[11, 22], [33, 44], [55, 66]]
<class 'numpy.ndarray'>


In [25]:
tupla = (1, 2, 3)
print(tupla)
print(type(tupla))

vector = np.array(tupla)
print(vector)
print(type(vector))

(1, 2, 3)
<class 'tuple'>
[1 2 3]
<class 'numpy.ndarray'>
