### Práctica 6: Matrice sparce (Con muchos ceros)

In [4]:
import numpy as np

In [5]:
n = 1000000
#A = np.random.rand(n, n)
v = np.random.rand(n)
print(f"A = \n {v}")

A = 
 [0.93867418 0.15955796 0.57929938 ... 0.0811877  0.58395002 0.32791512]


In [6]:
from scipy.sparse import csr_matrix

In [7]:
A = np.array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0]
])
print(f"A = \n {A}")

S = csr_matrix(A)
print(f"A en formato sparse = {S}")

B = S.todense()
print(f"B = \n {B}")

A = 
 [[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
A en formato sparse = <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (3, 6)>
  Coords	Values
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
B = 
 [[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


Veamos como introducir una matriz directamente a sparse

In [35]:
row = np.array([0, 0, 1, 1, 2])
col = np.array([0, 3, 2, 5, 3])
data = np.array([1, 1, 2, 1, 2])

mtx = csr_matrix((data, (row, col)), shape=(3, 6))
#print(f"Sparse matrix en formato csr = \n {mtx}")
#print(f"Misma matriz en formato dense = \n {mtx.todense()}")
print(f"Datos no nulos en la matriz en mtx = \n {mtx.data}")
print(f"Índices en mtx = \n {mtx.indices}")
print(f"Punteros para los índices de datos y filas = \n {mtx.indptr}")

Datos no nulos en la matriz en mtx = 
 [1 1 2 1 2]
Índices en mtx = 
 [0 3 2 5 3]
Punteros para los índices de datos y filas = 
 [0 2 4 5]


In [36]:
from scipy.sparse import csc_matrix

In [39]:
A = np.array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0]
])
print(f"A = \n {A}")

S = csc_matrix(A)
print(f"Matriz en formato sparse por columnas = \n {S}")

A = 
 [[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
Matriz en formato sparse por columnas = 
 <Compressed Sparse Column sparse matrix of dtype 'int64'
	with 5 stored elements and shape (3, 6)>
  Coords	Values
  (0, 0)	1
  (1, 2)	2
  (0, 3)	1
  (2, 3)	2
  (1, 5)	1


Concepto de sparsity (Medida del número  de elementos no nulos)


In [44]:
def sparsity(A):
    sparsi = 1.0 - np.count_nonzero(A) / A.size
    return sparsi

sparsity(A)
print(f"Sparsity de A = {sparsity(A)}")

Sparsity de A = 0.7222222222222222


Algunas matices sparse destacadas

In [45]:
from scipy import sparse

In [56]:
#print(f"Una matriz sparse con 1´s en la diagonal = \n {sparse.eye(10, 5)}")
#print(f"Una matriz identidad sparse = \n {sparse.identity(10)}")
print(f"Elementos no nulos de A = \n {sparse.find(A)}")


C = sparse.random(2, 2, density=(0.5))
print(f"C = \n {C}")

Elementos no nulos de A = 
 (array([0, 0, 1, 1, 2], dtype=int32), array([0, 3, 2, 5, 3], dtype=int32), array([1, 1, 2, 1, 2]))
C = 
 <COOrdinate sparse matrix of dtype 'float64'
	with 2 stored elements and shape (2, 2)>
  Coords	Values
  (1, 1)	0.9583850823386159
  (1, 0)	0.32463963502777127


Manipulacion de matrices desde ficheros de datos

In [57]:
sparse.save_npz("../data/random_sparse_matrix.npz", C)

In [63]:
D = sparse.load_npz("../data/random_sparse_matrix.npz")
print(f"D = \n {D}")

D = 
 <COOrdinate sparse matrix of dtype 'float64'
	with 2 stored elements and shape (2, 2)>
  Coords	Values
  (1, 1)	0.9583850823386159
  (1, 0)	0.32463963502777127
