### Práctica 3: Más sobre numpy array: index, slices, reshape, broadcasting, etc


In [1]:
import numpy as np

In [2]:
#array indexing
data = np.array([11, 12, 13, 14, 15])
print(data)
print(data[0])

data = np.array(
    [[11, 22],
    [33, 44],
    [55, 66]])
print(data)
print(data[0, 0])   #[Fila, columna]
print(data[0, :])   #Los : significa toda la fila
print(data[:, 1])   #Los : significa toda la columna



[11 12 13 14 15]
11
[[11 22]
 [33 44]
 [55 66]]
11
[11 22]
[22 44 66]


In [5]:
# array slicing

data = np.array([11, 22, 33, 44, 55])
print(data[1:4]) #Se selecciona desde el 1 al 4 sin incluir

data = np.array(
    [[11, 22],
    [33, 44],
    [55, 66]])
#Caracteristicas = X, etiquetas = y
X, y = data[:, :1], data[:, -1]
print(f"X = \n {X}")
print(f"y = \n{y}")

[22 33 44]
X = 
 [[11]
 [33]
 [55]]
y = 
[22 44 66]


In [4]:
data = np.array(
    [[11, 22, 33],
     [44, 55, 66],
     [77, 88, 99]])

split = 2
train, test = data[:split, :], data[split:, :]
print(f"Train = \n {train}")
print(f"Test = \n {test}")

Train = 
 [[11 22 33]
 [44 55 66]]
Test = 
 [[77 88 99]]


In [5]:
# array reshape
data =[
    [11, 12,],
    [33, 44],
    [55, 66]
]
data = np.array(data)
print(data.shape)
data = data.reshape((6, 1))
print(data)


(3, 2)
[[11]
 [12]
 [33]
 [44]
 [55]
 [66]]


In [11]:
# array broadcasting
a = np.array([1, 2, 3])
print(a)
b = 2
print(b)
c = a + b
print(c)

A = np.array([
    [1, 2, 3,],
    [1, 1, 1]
])
b = 2

C = A + b
print(C)

v = np.array([1, 2, 3])
D = A + v
print(D)

u = np.array([1, 1])
E = A + u
print(E)
#Para hacer broadcating tienen que tener la misma dimensión

[1 2 3]
2
[3 4 5]
[[3 4 5]
 [3 3 3]]
[[2 4 6]
 [2 3 4]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 